# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Path

# Directories to be prepended to $PATH
declare -a dirs_to_prepend
dirs_to_prepend=(
  "/usr/local/sbin"
  "/usr/local/mysql/bin"
  "$HOME/dotfiles/bin"
  "$HOME/bin"
  "$HOME/.mix/escripts"
  "$(brew --prefix ruby)/bin"
  "$(brew --prefix coreutils)/libexec/gnubin"       # Add brew-installed GNU core utilities bin
  "$(brew --prefix)/share/npm/bin"                  # Add npm-installed package bin
)

# Explicitly configured $PATH
PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

for dir in ${(k)dirs_to_prepend[@]}
do
  if [ -d ${dir} ]; then
    # If these directories exist, then prepend them to existing PATH
    PATH="${dir}:$PATH"
  fi
done

unset dirs_to_prepend

export PATH

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# User configuration

# Load the shell dotfiles
for file in $HOME/.{shell_exports,shell_aliases,shell_functions,shell_config}; do
  [ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;

if [ -f `brew --prefix`/etc/bash_completion ]; then
  . `brew --prefix`/etc/bash_completion
fi

# z is the new cd. https://github.com/rupa/z
. ~/z/z.sh

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# zplug

# init zplug
export ZPLUG_HOME=/usr/local/opt/zplug
source $ZPLUG_HOME/init.zsh

# zsh-history-substring-search
zplug "zsh-users/zsh-history-substring-search"
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

zplug "zsh-users/zsh-syntax-highlighting"

# powerline
# https://github.com/bhilburn/powerlevel9k
zplug "bhilburn/powerlevel9k", use:powerlevel9k.zsh-theme
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time root_indicator background_jobs history time)
#POWERLEVEL9K_CONTEXT_TEMPLATE="%n"
#POWERLEVEL9K_CONTEXT_TEMPLATE="%n@`hostname -f`"

zplug "plugins/git",   from:oh-my-zsh

# complete zplug setup
zplug install 2>/dev/null
zplug load

# nvm
export NVM_DIR="$HOME/.nvm"
source "/usr/local/opt/nvm/nvm.sh"

# SDKMAN
# THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/Users/ced/.sdkman"
[[ -s "/Users/ced/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/ced/.sdkman/bin/sdkman-init.sh"
